version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.3-php8.1-apache
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

volumes:
  db_data: {}
